# Generated by Django 6.0.1 on 2026-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active_semester',
            field=models.CharField(default='Semester 1', max_length=20),
        ),
    ]
